### ISSUE TITLE
vREPL occasionally hangs upon opening

### ISSUE THREAD

**Issue by paulober** [paulober/Pico-W-Go#105]
Sometimes the REPL occasionally hangs upon opening and causing the other commands (connect/disconnect, run, reset etc) to become unresponsive. Can't seem to find a reliable way to reproduce it.
<img width="814" alt="Screenshot 2023-04-13 at 3 18 51 pm" src="https://user-images.githubusercontent.com/319567/231660744-3274d4c5-dd49-4eea-981e-d95e28c9ee6c.png">

_Originally posted by @dburles in https://github.com/paulober/Pico-W-Go/issues/39#issuecomment-1506365738_

**Comment by paulober** [comment]
@dburles Does this still happen after v3.1.0?

**Comment by dburles** [comment]
Hey @paulober, I haven't been actively developing anything lately to confirm that, however I'll create a new issue if I encounter it again in future.

**Comment by paulober** [comment]
> Hey @paulober, I haven't been actively developing anything lately to confirm that, however I'll create a new issue if I encounter it again in future.

Ok, thanks.
