### ISSUE TITLE
pyIgnore is ignoring files in subdirectories or subdirectories in general

### ISSUE THREAD

**Issue by maxi07** [paulober/Pico-W-Go#111]
## What are the steps to reproduce this issue?
1. Open picowgo settings
2. Add a subdirectory to `picowgo.pyIgnore`

I have a directory similar to this
```
.
├── main.py
├── .gitignore
├── css
├── ...
└── modules/
    ├── module1.py
    ├── module2.py
    └── test_modules/
        ├── module3.py
        └── module5.py
```
I want to ignore `module2.py` and the whole directory `test_modules`. When adding a file or folder on root level, the file or folder is ignored as expected. But when adding `modules/module2.py` or `modules/test_modules` the file and folder are still uploaded. I also tried other filepath styles, eg `modules\\module2.py` and restarting vscode after editing the extension settings, but without any success.

## What happens?
The subdirectory is not ignored and still uploaded

## What were you expecting to happen?
I was expecting to add subdirectories or even specific files in subdirectories to ignore.

## Any logs, error output, etc?
None

## Which version of Pico-W-Go are you using?
3.1.1

## Support info
```
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Datum: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Windows_NT x64 10.0.22621
```

Thanks for the awesome extension btw, especially with v3!

Edit: I am editing pyIgnore in a workspace

**Comment by paulober** [comment]
Maybe "**/.git" for excluding git in every directory and else relative paths...
