### ISSUE TITLE
When connected for keyboard shortcuts

### ISSUE THREAD

**Issue by JoeSc** [paulober/Pico-W-Go#29]
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.
vscode allows me to map `picowgo.run` to `ctrl+enter`  However I have not been able to find a way to set the "When" for the shortcut to "When picowgo is connected" or something similar

## Describe the solution you'd like
Assistance with setting the "When" or perhaps picowgo has to export a variable that can be used in the "When" field

## Describe alternatives you've considered
I can set the shortcut to `ctrl+enter`, but then that breaks jupyter notebooks I may be working on

**Comment by paulober** [comment]
Hi, thanks for the feedback and sorry for the delay. I'll look into it.

**Comment by PabloPoche** [comment]
Cuando se esta auto-ejecutando un script(main.py) en la raspberry pico W, es muy dificil conectarce (Pico-W-Go > Connect) para deterner su ejecucion y el status de coneccion siempre dice:  Pico W Disconnected

**Comment by paulober** [comment]
@JoeSc You can now check for the extension being active with `pico-w-go.isActivated` or for it being connected to a Pico with `pico-w-go.isConnected` in a when-clause context. 
Changes will be published with release v3.2.0.
