### ISSUE TITLE
Typo in Pico-W-Stub/stdlib/socket.pyi

### ISSUE THREAD

**Issue by blakeglucas** [paulober/Pico-W-Go#35]
Current file contents are 

```python
from .socket import *
```

which obviously doesn't make sense. Problem is resolved by changing to

```python
from .usocket import *
```

Will submit a PR with fix, just posting issue for tracking purposes.

**Comment by paulober** [comment]
Thanks for mentioning. 
Fixed with [45c00bc](https://github.com/paulober/Pico-W-Go/commit/45c00bc4d2ec77647a17236aa1dd5c316e0619be)...
