### ISSUE TITLE
Config additional sync folders per project

### ISSUE THREAD

**Issue by plesatejvlk** [paulober/Pico-W-Go#40]
# Feature Request 🚀

As I manage multiple pico-w projects in the same repository I would appreciate a config setting which would allow me to:
- set the syncFolder per directory (already supported)
- allow for "contents only" sync on the "Upload Project" action, for example:
```
repository-name
-- project-one
---- .picowgo (syncFolder="project-one")
---- main.py
-- project-two
---- .picowgo (syncFolder="project-two")
---- main.py
```
I would expect that once running the "Upload Project" action from within the `project-one` directory the `project-one/main.py` would get uploaded as `/main.py` to the pico (treating the `syncFolder` setting as a project target root).

Thanks for considering this!

**Comment by paulober** [comment]
Sorry for having overlooked this issue for so long. Now that V3 of the extension is here. I'll take your request on the TODO list. I'll keep you updated.

**Comment by ffunenga** [comment]
Is there a work around available until this issue is resolved? For now, the only way I am seeing to overcome this problem is to *only* use the Pico-W-FS and write my code directly there.

**Comment by paulober** [comment]
@ffunenga I'm working on adding support for multi root projects but for now you can either open only the directory with the project you want to upload or set the syncRoot in the  workspace `settings.json` to the project folder you are currently working on.
