### ISSUE TITLE
Add command to list files inside Pico

### ISSUE THREAD

**Issue by busslina** [paulober/Pico-W-Go#48]
Like it does Ampy: `ampy --port com3 ls`

**Comment by rdhuff** [comment]
Amen! Thonny has this feature, always has, and it needs to be implemented.

**Comment by paulober** [comment]
Woking on it...

**Comment by paulober** [comment]
@busslina, @rdhuff and anyone else waiting for this feature. I think the new remote workspace integration with V3 of the extension should satisfy your need.
