### ISSUE TITLE
'run' button in VSCode terminal window doesn't change to 'stop' button so code execution cannot be halted

### ISSUE THREAD

**Issue by Tonyindahouse** [paulober/Pico-W-Go#58]
## What are the steps to reproduce this issue?
Connecting a Pico W and running unchanged code.

## What happens?
In the previous version, the status bar at the bottom of VSCode (light blue in the attached image) has a 'Run' button, which begins execution of the active file. Once running, this button used to change to a 'Stop' button, which halted execution. The button now does not change to 'Stop' and still says 'Run'. Clicking the button does NOT stop the code now. There seems to be no way to stop the code running other than disconnecting the Pico.

## What were you expecting to happen?
'Run'' would change to 'Stop' and clicking 'Stop' would halt code execution (ie unchanged from last version).

## Any logs, error output, etc?
None.

## Any other comments?
None.

## Support info
Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

![Screenshot 2023-04-10 205049](https://user-images.githubusercontent.com/59253296/230985339-fae1dfba-861d-4bc1-bfc1-6056f1f9f33e.jpg)

**Comment by paulober** [comment]
Thanks for the quick report. I'll take a look. Stay tuned for an update on this issue.
