### ISSUE TITLE
Can't ignore project.pico-w-go when uploading project

### ISSUE THREAD

**Issue by FroztOfficial** [paulober/Pico-W-Go#72]
## What are the steps to reproduce this issue?
1. Open VS-Code
2. Open settings for Pico-W-Go extension
3. Add "project.pico-w-go" to "Py Ignore"
4. Restart VS-Code
5. Run "Pico-W-Go > Upload project" command
6. Open python terminal for the Raspberry Pi Pico W
7. Type in the following commands in the python terminal
```
>>> import os
>>> os.listdir()
```
8. This now shows the "project.pico-w-go" in the list of files on the Raspberry Pi Pico W, which should be ignore by the "Py Ignore" setting.

## What happens?
It does not ignore the "project.pico-w-go" file, even tho it should be ignored by using the "Py Ignore" from the extension settings.

## What were you expecting to happen?
It should not show the "project.pico-w-go" file on the Raspberry Pi Pico W.

## Any logs, error output, etc?
No errors shown in "Terminal > Output > Protocol (Extension Host)".

## Any other comments?
* I am running Pico-W-Go version "2.1.8", because if using any newer, then the"Pico-W-Go > Configure project" command would not be able to run with success.
* As you can see the "project.pico-w-go" file is also not stored in the project directory:
![image](https://user-images.githubusercontent.com/51519573/232247074-c9495bee-50bc-4731-82ae-f68ace8ebb89.png)

**Comment by paulober** [comment]
remove the file on the pico with the os module. What is you error output in Output > "Extension Host" when configure project fails for you with v3+?
