### ISSUE TITLE
Pico-Go status bar is visible in non-pico projects

### ISSUE THREAD

**Issue by timstrasser** [paulober/Pico-W-Go#9]
## What are the steps to reproduce this issue?
1. Install extension
2. Open any folder in VSCode

## What happens?
The Pico-Go status bar appears, no matter if the current folder is a Pico project or not.

## What were you expecting to happen?
I would expect the Pico-Go extension, to be loaded only if I'm inside a Pico project.

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## Support info

Copy this from the `Pico-W-Go > Help > Get support info` option in the command palette:

```
Get support info" does not print anything into console.
```

**Comment by paulober** [comment]
I'm also anoyed by this behaviour and try to fix this in an upcoming version. Thanks for mentioning...

**Comment by timstrasser** [comment]
Thanks. :) If I'm not mistaken, this problem did not occur in the latest cpwood repo. I'm not sure what caused the issue, though.

**Comment by paulober** [comment]
Ok, that's wired... As mentioned in #8 I'm currently working on a clean re-write with up-to date dependencies etc.... Should I make good progress with this this should probably fix a lot of these issues.

**Comment by timstrasser** [comment]
Looking forward to that! Do you plan on also rewriting the automation scripts? (e.g. for generating the stubs and the bindings)

**Comment by paulober** [comment]
Maybe via my Azure DevOps, but that depends on the dependency I will use for serial communication. For example the current serialport package does not work in its latest version with the extension so maybe there are some changes in the requirement for the native bindings. And no, I probably won't rewrite the script that generates the stubs on the pico, if that's what you mean. I was thinking of reusing the stubs repo that already exists and just rewriting the extension and the communication between the three parts. If I have enough time for it...

**Comment by paulober** [comment]
Should be fixed since update 2.0.0, can you confirm?

**Comment by paulober** [comment]
After 7 days of no response, I will mark this issue as closed. If the issue has not been resolved, feel free to reopen it.
