### ISSUE TITLE
Adding buttons to status bar

### ISSUE THREAD

**Issue by KristianBalaj** [paulober/Pico-W-Go#95]
I'm trying to add new items to status bar but I'm struggling to get the right keywords.

What are the options for `picowgo.statusbarButtons` setting?
I'd like to add `Upload project` and `Toggle Virtual file system` specifically.

**Comment by paulober** [comment]
@KristianBalaj See https://github.com/paulober/Pico-W-Go/blob/08b3cd6abf6209056694ccf3306cf6108a75b9c4/package.json#L326-L393 for valid keys.

An item for "Toggle Virtual file system/workspace" will be added with a future patch.
